In [1]:
import pandas as pd 
import numpy as np 
import datetime as dt 
import random 
import matplotlib.pyplot as plt 
import time
%matplotlib inline

Read the file, strip the white columns and check the info.

In [2]:
rc = pd.read_csv('rollercoaster.csv')
rc.columns = rc.columns.str.strip()
rc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 20 columns):
Name                        300 non-null object
Park                        300 non-null object
City/Region                 300 non-null object
City/State/Region           300 non-null object
Country/Region              300 non-null object
Geographic Region           300 non-null object
Construction                300 non-null object
Type                        300 non-null object
Status                      300 non-null object
Year/Date Opened            300 non-null int64
Height (feet)               299 non-null object
Speed (mph)                 296 non-null float64
Length (feet)               295 non-null float64
Inversions (YES or NO)      300 non-null object
Number of Inversions        300 non-null int64
Drop (feet)                 142 non-null object
Duration (min:sec)          224 non-null object
G Force                     83 non-null object
Vertical Angle (degrees)    91 non-null float64
CoasterBuzz Ranking         69 non-null float64
dtypes: float64(4), int64(2), object(14)
memory usage: 47.0+ KB

In [3]:
rc.columns

Index(['Name', 'Park', 'City/Region', 'City/State/Region', 'Country/Region',
       'Geographic Region', 'Construction', 'Type', 'Status',
       'Year/Date Opened', 'Height (feet)', 'Speed (mph)', 'Length (feet)',
       'Inversions (YES or NO)', 'Number of Inversions', 'Drop (feet)',
       'Duration (min:sec)', 'G Force', 'Vertical Angle (degrees)',
       'CoasterBuzz Ranking'],
      dtype='object')

From the info report, we noticed that the columns "Drop(feet)", "G Force", "Vertical Angle (degrees)" and "CoasterBuzz Ranking" have fewer than half of the valuable data. So we decide to get rid of these columns.

In [4]:
rc_ranking = rc.drop(columns = ['Drop (feet)', 'G Force', 'Vertical Angle (degrees)'])
print(rc_ranking.info())
rc = rc_ranking.drop(columns = "CoasterBuzz Ranking")
print(rc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 17 columns):
Name                      300 non-null object
Park                      300 non-null object
City/Region               300 non-null object
City/State/Region         300 non-null object
Country/Region            300 non-null object
Geographic Region         300 non-null object
Construction              300 non-null object
Type                      300 non-null object
Status                    300 non-null object
Year/Date Opened          300 non-null int64
Height (feet)             299 non-null object
Speed (mph)               296 non-null float64
Length (feet)             295 non-null float64
Inversions (YES or NO)    300 non-null object
Number of Inversions      300 non-null int64
Duration (min:sec)        224 non-null object
CoasterBuzz Ranking       69 non-null float64
dtypes: float64(3), int64(2), object(12)
memory usage: 39.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
Name                      300 non-null object
Park                      300 non-null object
City/Region               300 non-null object
City/State/Region         300 non-null object
Country/Region            300 non-null object
Geographic Region         300 non-null object
Construction              300 non-null object
Type                      300 non-null object
Status                    300 non-null object
Year/Date Opened          300 non-null int64
Height (feet)             299 non-null object
Speed (mph)               296 non-null float64
Length (feet)             295 non-null float64
Inversions (YES or NO)    300 non-null object
Number of Inversions      300 non-null int64
Duration (min:sec)        224 non-null object
dtypes: float64(2), int64(2), object(12)
memory usage: 37.6+ KB
None

In [5]:
# finding rows with missing values
rc[(rc['Height (feet)'].isnull() == True) | (rc['Speed (mph)'].isnull() == True) | (rc['Length (feet)'].isnull() == True) | (rc['Duration (min:sec)'].isnull() == True)]

,Name,Park,City/Region,City/State/Region,Country/Region,Geographic Region,Construction,Type,Status,Year/Date Opened,Height (feet),Speed (mph),Length (feet),Inversions (YES or NO),Number of Inversions,Duration (min:sec)
2,Adrenaline Peak,Oaks Amusement Park,Portland,Oregon,United States,North America,Steel,Sit Down,Operating,2018,72,45.0,1050.0,YES,3,NaN
5,Alpina Blitz,Nigloland,Dolancourt,Champagne-Ardenne,France,Europe,Steel,Sit Down,Operating,2014,108.3,51.6,2358.9,NO,0,NaN
6,Altair,CinecittË† World,Rome,Rome,Italy,Europe,Steel,Sit Down,Operating,2014,108.3,52.8,2879.8,YES,10,NaN
28,Behemoth,Canada's Wonderland,Vaughan,Onterio,Canada,North America,Steel,Sit Down,Operating,2008,230,77.0,5318.0,NO,0,NaN
30,Big Loop,Heide-Park Resort,Soltau,Lower Saxony,Germany,Europe,Steel,Sit Down,Operating,1983,98.4,39.2,2316.3,YES,4,NaN
35,Black Mamba,Phantasialand,Bruhl,North Rhine-Westphalia,Germany,Europe,Steel,Inverted,Operating,2006,85.3,49.7,2519.7,YES,4,NaN
39,Boardwalk Bullet,Kemah Boardwalk,Kemah,Texas,United States,North America,Wood,Sit Down,Operating,2007,96,51.0,3236.0,NO,0,NaN
40,Bocaraca,Parque de Diversiones,La Uruca,San Jose,Costa Rica,Central America,Steel,Sit Down,Operating,2005,64,37.3,1148.3,YES,2,NaN
51,Boss,Six Flags St. Louis,Eureka,Missouri,United States,North America,Wood,Sit Down,Operating,2000,122,66.3,4631.0,NO,0,NaN
53,Bullet Coaster,Happy Valley,Nanshan,"Shenzhen, Guanagdong",China,Asia,Steel,Sit Down,Operating,2012,196.8,83.0,NaN,NO,0,NaN
64,Crazy Bird,Happy Valley,Dongli,Tianjin,China,Asia,Steel,Sit Down,Operating,2013,98.4,NaN,1279.5,YES,2,NaN
65,Crazy Coaster,Loca Joy Holiday Theme Park,Yongchuan,Chongqing,China,Asia,Steel,Sit Down,Operating,2013,108.3,52.8,2870.8,YES,10,NaN
73,Dinoconda,China Dinosaurs Park,Xinbei,"Changzhou, Jiangsu",China,Asia,Steel,Wing,Operating,2012,226.4,78.3,3444.9,YES,3,NaN
74,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,Asia,Steel,Sit Down,Operating,2001,160.8,111.8,4081.3,YES,1,NaN
75,Doble Loop,Salitre Magico,Bogota,Cundinamarca,Colombia,South America,Steel,Sit Down,Operating,2004,59.1,56.0,2822.0,YES,2,NaN
78,Dragon's Run,Dragon Park,Ha Long,Quang Ninh,Vietnam,Asia,Steel,Sit Down,Operating,2017,150,65.0,3738.0,YES,6,NaN
81,El Toro,Freizeitpark Plohn,Lengenfeld,Saxony,Germany,Europe,Wood,Sit Down,Operating,2009,80.5,45.6,2379.0,NO,0,NaN
84,Extreme Rusher,Happy Valley,Chaoyang,Beijing,China,Asia,Steel,Sit Down,Operating,2011,170.6,83.0,2788.8,NO,0,NaN
94,Flight of the Phoenix,Harborland,Beilun,"Ningbo, Shejiang",China,Asia,Steel,Sit Down,Operating,2006,101.7,49.7,2723.1,YES,8,NaN
95,Fluch von Novgorod,Hansa Park,Sierksdorf,Schleswig-Holstein,Germany,Europe,Steel,Sit Down,Operating,2009,131.3,62.1,2296.6,YES,1,NaN
97,Flying Aces,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates,Middle East,Steel,Sit Down,Operating,2016,206.7,74.6,4921.3,YES,1,NaN
99,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates,Middle East,Steel,Sit Down,Operating,2010,170.6,149.1,6561.7,NO,0,NaN
103,Fury 325,Carowinds,Charlotte,North Carolina,United States,North America,Steel,Sit Down,Operating,2015,325,95.0,6602.0,NO,0,NaN
109,Giant Dipper,Belmont Park,San Diego,California,United States,North America,Wood,Sit Down,Operating,1925,73,55.0,2600.0,NO,0,NaN
111,Goliath,Six Flags Over Georgia,Austell,Georgia,United States,North America,Steel,Sit Down,Operating,2006,200 ft,70.0,4480.0,NO,0,NaN
114,Goliath,Six Flags Great America,Gurnee,Illinois,United States,North America,Wood,Sit Down,Operating,2014,165,72.0,3100.0,YES,2,NaN
117,Green Lantern Coaster,Warner Bros. Movie World,Gold Coast,Queensland,Australia,Oceana,Steel,Sit Down,Operating,2011,108.3,41.0,1601.1,YES,2,NaN
120,Hades 360,Mt. Olympus Water & Theme Park,Wisconsin Dells,Wisconsin,United States,North America,Wood,Sit Down,Operating,2005,136,60.0,4746.0,YES,1,NaN
122,Happy Angel,Wanda Theme Park,Harbin,Heilongjiang,China,Asia,Steel,Inverted,Operating,2017,NaN,54.1,NaN,YES,6,NaN
126,Hyper Coaster,Land of Legends Theme Park,Antalya,Antalya,Turkey,Europe,Steel,Sit Down,Operating,2018,200.2,71.5,4176.5,YES,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,RailBlazer,California's Great America,Santa Clara,California,United States,North America,Steel,Sit Down,Operating,2018,106,52.0,1800.0,YES,3,NaN
203,Ranier Rush,Puyallup Fair,Puyallup,Washington,United States,North America,Steel,Sit Down,Operating,2013,63,45.0,1775.0,YES,1,NaN
208,Red Force,Ferrari Land,Salou,Tarragona,Spain,Europe,Steel,Sit Down,Operating,2017,367.3,111.8,2887.2,NO,0,NaN
218,Schwur des KÅ rnan,Hansa Park,Sierksdorf,Schleswig-Holstein,Germany,Europe,Steel,Sit Down,Operating,2015,239.5,78.9,4051.8,YES,1,NaN
228,Skyrush,Hersheypark,Hershey,Pennsylvania,United States,North America,Steel,Sit Down,Operating,2012,200,75.0,3600.0,NO,0,NaN
231,Soaring Dragon & Dancing Phoenix,Nanchang Wanda Theme Park,Xinjian,"Nanchang, Jiangxi",China,Asia,Steel,Inverted,Operating,2016,196.8,84.0,4192.0,YES,6,NaN
236,Star Mountain,Beto Carrero World,Penha,Santa Catarina,Brazil,South America,Steel,Sit Down,Operating,1993,75,40.0,2400.0,YES,2,NaN
238,Stealth,Thorpe Park,Chertsey,"Surrey, England",United Kingdom,Europe,Steel,Sit Down,Operating,2006,205.1,80.0,1312.3,NO,0,NaN
243,Steel Venom,Valleyfair!,Shakopee,Minnesota,United States,North America,Steel,Inverted,Operating,2003,185,68.0,630.0,NO,0,NaN
247,Super Tornado,Zoo Safari- und Hollywoodpark Stukenbrock,Stukenbrock,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,1981,64,37.3,1148.3,YES,2,NaN
256,T Express,Everland,Yongin-si,Gyeonggi-do,South Korea,Asia,Wood,Sit Down,Operating,2008,183.8,64.6,5383.8,NO,0,NaN
258,Talon,Dorney Park & Wildwater Kingdom,Allentown,Pennsylvania,United States,North America,Steel,Inverted,Operating,2001,135,58.0,3110.0,YES,4,NaN
259,Taron,Phantasialand,Bruhl,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,2016,98.4,72.7,4330.8,NO,0,NaN
260,Tatsu,Six Flags Magic Mountain,Valencia,California,United States,North America,Steel,Flying,Operating,2006,170,62.0,3602.0,YES,4,NaN
264,Texas Tornado,Wonderland Amusement Park,Amarillo,Texas,United States,North America,Steel,Sit Down,Operating,1985,80,65.0,2050.0,YES,2,NaN
266,Timber Drop,Fraispertuis City,Jeanmenil,Lorraine,France,Europe,Steel,Sit Down,Operating,2011,96,41.0,NaN,YES,2,1:20
268,Timberhawk: Ride of Prey,Wild Waves Theme Park,Federal Way,Washington,United States,North America,Wood,Sit Down,Operating,2003,75,50.0,2600.0,NO,0,NaN
271,Titan Cascabel,Selva Magica,Guadalajara,Jalisco,Mexico,Central America,Steel,Sit Down,Operating,1994,75,55.0,2500.0,NO,0,NaN
274,Tornado,Bosque Magico,Guadalupe,Nuevo Leon,Mexico,Central America,Steel,Sit Down,Operating,2001,64,37.3,1148.3,YES,2,NaN
277,Twister II,Elitch Gardens,Denver,Colorado,United States,North America,Wood,Sit Down,Operating,1995,100,55.0,4640.0,NO,0,NaN
278,Ultimate,Lightwater Valley,Ripn,"North Yorkshire, England",United Kingdom,Europe,Steel,Sit Down,Operating,1991,107,50.0,7442.0,NO,0,NaN
279,V2: Vertical Velocity,Six Flags Discovery Kingdom,Vallejo,California,United States,North America,Steel,Sit Down,Operating,2001,150,65.0,630.0,NO,0,NaN
280,Valravn,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Sit Down,Operating,2016,223,75.0,3415.0,YES,3,NaN
282,Velikolukskiy Myasokombinat-2,Wonder Island,Saint Petersburg,Saint Petersburg,Russia,Europe,Steel,Sit Down,Operating,2017,108,52.8,2870.0,YES,10,NaN
283,Vertical Velocity,Six Flags Great America,Gurnee,Illinois,United States,North America,Steel,Inverted,Operating,2001,185,70.0,630.0,NO,0,NaN
288,Whirl Wind Looping Coaster,Wonder Island,Saint Petersburg,Saint Petersburg,Russia,Russia,Steel,Sit Down,Operating,2003,64,37.3,1148.0,YES,2,NaN
290,Wicked Cyclone,Six Flags New England,Agawam,Massachusetts,United States,North America,Steel,Sit Down,Operating,2015,109,55.0,3320.0,YES,3,NaN
291,Wicked Twister,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Inverted,Operating,2002,215,72.0,215.0,NO,0,NaN
296,Winjas,Phantasialand,Bruhl,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,2002,57.1,41.0,1526.6,NO,0,NaN
298,X2,Six Flags Magic Mountain,Valencia,California,United States,North America,Steel,Wing,Operating,2002,175,76.0,3610.0,YES,2,NaN

In [6]:
for i in range(len(rc)):
    try:
        float(rc['Height (feet)'][i])
    except:
        print(i, rc['Height (feet)'][i])

111 200 ft

In [7]:

rc.loc[111, 'Height (feet)'] = 200
rc.iloc[111]

Name                                     Goliath
Park                      Six Flags Over Georgia
City/Region                              Austell
City/State/Region                        Georgia
Country/Region                     United States
Geographic Region                  North America
Construction                               Steel
Type                                    Sit Down
Status                                Operating
Year/Date Opened                            2006
Height (feet)                                200
Speed (mph)                                   70
Length (feet)                               4480
Inversions (YES or NO)                        NO
Number of Inversions                           0
Duration (min:sec)                           NaN
Name: 111, dtype: object

We want to fill in the NaN values with the mean of their corresponding columns.

In [8]:
#rc['Duration (min:sec)'] = rc['Duration (min:sec)'].replace(r'^\s+$', np.nan, regex=True)
#rc['Duration (min:sec)'] = pd.to_datetime(rc['Duration (min:sec)'])
#rc['Duration (min:sec)'].min

In [10]:
rc['Speed (mph)'].fillna((rc['Speed (mph)'].mean()),inplace = True)
rc['Length (feet)'].fillna((rc['Length (feet)'].mean()),inplace = True)
rc['Height (feet)'] = rc['Height (feet)'].astype(float)
rc['Height (feet)'].fillna((rc['Height (feet)'].mean()),inplace = True)
#rc[rc['Duration (min:sec)'].isnull() == False]['Duration (min:sec)'] = pd.to_datetime(rc[rc['Duration (min:sec)'].isnull() == False]['Duration (min:sec)'])


#rc['Duration (min:sec)'] = rc['Duration (min:sec)'].replace(r'^\s+$', np.nan, regex=True)

for m in range(len(rc)):
    try:
        value = rc['Duration (min:sec)'][m].split(':')
        i = 60
        total_sec = 0
        for numbers in value:
            total_sec += i*int(numbers)
            i = 1
        rc.loc[m, 'Duration (min:sec)'] = int(total_sec)
    except:
        pass

rc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
Name                      300 non-null object
Park                      300 non-null object
City/Region               300 non-null object
City/State/Region         300 non-null object
Country/Region            300 non-null object
Geographic Region         300 non-null object
Construction              300 non-null object
Type                      300 non-null object
Status                    300 non-null object
Year/Date Opened          300 non-null int64
Height (feet)             300 non-null float64
Speed (mph)               300 non-null float64
Length (feet)             300 non-null float64
Inversions (YES or NO)    300 non-null object
Number of Inversions      300 non-null int64
Duration (min:sec)        223 non-null float64
dtypes: float64(4), int64(2), object(10)
memory usage: 37.6+ KB